server:
  port: 10010

spring:
  application:
    name: gateway
  cloud:
    nacos:
      #访问nacos的地址
      server-addr: localhost:8848
    gateway:
      routes:  #网关路由配置
        - id: user-service  #路由id，自定义，只要唯一即可
        #url：http://127.0.0.1:8081 路由的目标地址http就是固定地址(这种写死的规则我们一般不使用)
          uri: lb://userservice #路由的目标地址lb就是负载均衡，后面跟服务名称   lb:loadBalance
          predicates:
            - Path=/user/** # 按照路径匹配，只要以/user/开头就符合要求
        - id: order-service
          uri: lb://orderserver
          predicates:
            - Path=/order/**
            - Before=2031-04-13T15:14:47.433+08:00[Asia/Shanghai]
      default-filters:
        - AddRequestHeader=Truth, it is work