server:
  port: 8080
spring:
  application:
    name: order-server
  datasource:
    url: jdbc:mysql://192.168.26.130:3306/cloud-order?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      server-addr: 192.168.26.130:8848
      discovery:
        cluster-name: HZ
        namespace: d02e08ec-0a40-4c94-8161-146ee48ad33b
        ephemeral: true

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS


#eureka:
#  client:
#    #是否从eureka中抓取注册信息
#    fetch-registry: true
#    #使用eureka注册
#    register-with-eureka: true
#    service-url:
#      defaultZone: http:ost:10086/eureka

user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

ribbon:
  eager-load:
    enabled: true #开启饥饿加载
    clients: user-service  #指定饥饿加载的服务名称

    #如果有多个服务
    #clients:
        #- XXXXXXX
        #- XXXXXXX
