spring:
  application:
    name: erueka-server


eureka:
  client:
    service-url:
        defaultZone: http://127.0.0.1:10086/erueka
server:
  port: 10086

    fetch-registry: false
    register-with-eureka: false