spring:
  application:
    name: erueka-server


eureka:
  client:
    service-url:
        defaultZone: http://127.0.0.1:10086/erueka
#    fetch-registry: false
#    register-with-eureka: false

server:
  port: 10086